version: "3.3"

services:
    # DNS Server
    coredns:
        image: coredns/coredns
        container_name: coredns
        ports:
            - "53:53/udp"
        volumes:
            - /srv/docker/coredns/config/:/config
            - /srv/docker/coredns/zones/:/zones
        command: -conf /config/Corefile
        restart: unless-stopped

    # Manual HTTP(S) server
    caddy:
        image: caddy
        container_name: caddy
        volumes:
            - /srv/docker/caddy/config/:/config
            - /srv/docker/caddy/data/:/data
            - /srv/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
            - /srv/http:/srv/http
            - /srv/ssl/caddy:/ssl
        ports:
            - "80:80"
            - "443:443"
        restart: unless-stopped
        depends_on:
            - coredns

    # # Secure secrets management
    # vault:
    #     image: vault
    #     container_name: vault
    #     volumes:
    #         - /srv/docker/vault/config:/vault/config
    #         - /srv/ssl/vault/cert:/ssl
    #     ports:
    #         - "8200:8200"
    #         - "8201:8201"
    #     cap_add:
    #         - IPC_LOCK
    #     restart: unless-stopped
    #     depends_on:
    #         - caddy
    #         - consul

    # Service management
    consul:
        image: consul
        container_name: consul
        volumes:
            - /srv/docker/consul:/consul
        network_mode: host
        restart: unless-stopped
        depends_on:
            - caddy

    # # Automatic HTTP(S) server and TCP proxy
    # fabio:
    #     image: fabiolb/fabio
    #     container_name: fabio
    #     restart: unless-stopped
    #     depends_on: caddy
