version: "3.3"

services:
    # Service management
    consul:
        image: consul
        container_name: consul
        volumes:
            - /srv/docker/consul/config:/consul/config
            - /srv/docker/consul/data:/consul/data
            - /srv/ssl/consul:/ssl:ro
            - /etc/ssl/certs:/etc/ssl/certs:ro
        network_mode: host
        restart: unless-stopped
        depends_on:
            - coredns

    # DNS Server
    coredns:
        image: coredns/coredns
        container_name: coredns
        ports:
            - "53:53/udp"
        volumes:
            - /srv/docker/coredns/config/:/config:ro
            - /srv/docker/coredns/zones/:/zones:ro
            - /etc/ssl/certs:/etc/ssl/certs:ro
        command: -conf /config/Corefile
        restart: unless-stopped

    # Automatic HTTP(S) server and TCP proxy
    fabio:
        image: fabiolb/fabio
        container_name: fabio
        network_mode: host
        volumes:
            - /srv/docker/fabio/config/:/etc/fabio:ro
            - /srv/ssl/fabio:/ssl:ro
            - /etc/ssl/certs:/etc/ssl/certs:ro
        command: -cfg /etc/fabio/fabio.properties -insecure
        restart: unless-stopped
        depends_on:
            - consul

    # Secure secrets management
    vault:
        image: vault
        container_name: vault
        volumes:
            - /srv/docker/vault/config:/vault/config
            - /srv/ssl/vault:/ssl:ro
            - /etc/ssl/certs:/etc/ssl/certs:ro
        network_mode: host
        cap_add:
            - IPC_LOCK
        command: server
        restart: unless-stopped
        depends_on:
            - consul
